=== LuckerCxd/CxdRepository/进阶笔记/笔记2/Jsoup&&xml/附件/Person.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT persons (person+)>
<!ELEMENT person (id,name,sex)>
<!ELEMENT id (#PCDATA) >
<!ELEMENT name (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ATTLIST person number ID #REQUIRED>

=== LuckerCxd/CxdRepository/进阶笔记/笔记2/Jsoup&&xml/附件/BaseDtdXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons SYSTEM "Person.dtd">
<persons>
	<person number  ="ss">
		<id>001</id>
		<name id = "first">lixiao</name>
		<sex>female</sex>
	</person>
	<person number  ="s1">
		<id>001</id>
		<name>chenxiao</name>
		<sex>female</sex>
	</person>
</persons>
